version: 2
jobs:
  build:
    steps:
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests

      - store_artifacts:
          path: test-reports
          destination: test-reports
